### ISSUE TITLE
cleanup-db problem when querying some airflow db models

### ISSUE THREAD

**Issue by juanfassio** [teamclairvoyant/airflow-maintenance-dags#138]
The dag is having issues when trying to execute cleanup on the following DB Objects:
TaskInstance
BaseXCom
TaskReschedule
RenderedTaskInstanceFields

this is are the logs the task cleanup_TaskInstance

[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:268} INFO - Retrieving max_execution_date from XCom
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:281} INFO - Configurations:
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:282} INFO - max_date:                 2023-12-10 14:14:20.828289+00:00
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:283} INFO - enable_delete:            True
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:284} INFO - session:                  <sqlalchemy.orm.session.Session object at 0x7f95267817f0>
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:285} INFO - airflow_db_model:         <class 'airflow.models.taskinstance.TaskInstance'>
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:286} INFO - state:                    None
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:287} INFO - age_check_column:        ColumnAssociationProxyInstance(AssociationProxy('dag_run', 'execution_date'))
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:288} INFO - keep_last:                True
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:289} INFO - keep_last_filters:        None
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:290} INFO - keep_last_group_by:       None
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:292} INFO - 
[2024-01-09, 14:15:24 UTC] {airflow_db_cleanup.py:294} INFO - Running Cleanup Process...
[2024-01-09, 14:15:24 UTC] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/env/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/env/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/airflow_db_cleanup.py", line 301, in cleanup_function
    logging.info("INITIAL QUERY : " + str(query))
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2946, in __str__
    return str(statement.compile(bind))
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 503, in compile
    return self._compiler(dialect, **kw)
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 567, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 809, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 464, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 499, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 3405, in visit_select
    compile_state = select_stmt._compile_state_factory(
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/sql/base.py", line 510, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 736, in create_for_statement
    opt.process_compile_state(self)
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/orm/strategy_options.py", line 263, in process_compile_state
    self._process(
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/orm/strategy_options.py", line 920, in _process
    val._bind_loader(
  File "/home/env/lib/python3.8/site-packages/sqlalchemy/orm/strategy_options.py", line 1084, in _bind_loader
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: mapper option expects string key or list of attributes

Im using Airflow 2.5.3

**Comment by juanfassio** [comment]
Changed the "age_check_column"'s value for TaskInstance, XCom, TaskReschedule, RenderedTaskInstanceFields as follows:
TaskInstance.execution_date                         -> TaskInstance.run_id
XCom.execution_date                                   -> XCom.timestamp
TaskReschedule.execution_date                    -> TaskReschedule.run_id
RenderedTaskInstanceFields.executio_date  -> RenderedTaskInstanceFields.run_id
