### ISSUE TITLE
cleanup_DagRun crash

### ISSUE THREAD

**Issue by Stormhand** [teamclairvoyant/airflow-maintenance-dags#52]
The SQL query throws an exception when trying to delete dag runs:

> [2019-09-13 11:58:27,276] {logging_mixin.py:95} INFO - [2019-09-13 11:58:27,276] {airflow-db-cleanup.py:134} INFO - Process will be Deleting 143 DagRun(s)
[2019-09-13 11:58:27,276] {logging_mixin.py:95} INFO - [2019-09-13 11:58:27,276] {airflow-db-cleanup.py:137} INFO - Performing Delete...
[2019-09-13 11:58:27,277] {taskinstance.py:1047} ERROR - (_mysql_exceptions.OperationalError) (1093, "You can't specify target table 'dag_run' for update in FROM clause")
[SQL: DELETE FROM dag_run WHERE dag_run.execution_date NOT IN (SELECT max(dag_run.execution_date) AS max_1 
FROM dag_run GROUP BY dag_run.dag_id) AND dag_run.execution_date <= %s]
[parameters: (datetime.datetime(2019, 8, 14, 8, 56, 48, 619622, tzinfo=<TimezoneInfo [UTC, GMT, +00:00:00, STD]>),)]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/home/airflow/venv37/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/venv37/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/venv37/lib/python3.7/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/home/airflow/venv37/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/airflow/venv37/lib/python3.7/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/home/airflow/venv37/lib/python3.7/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/home/airflow/venv37/lib/python3.7/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1093, "You can't specify target table 'dag_run' for update in FROM clause")

Airflow 1.10.4

**Comment by sudhakar-nallam** [comment]
@Stormhand Can you please share more details.
1. MySQL version?
2. SQL client library version?

**Comment by Stormhand** [comment]
Sorry i fixed it using the queries in this closed issue https://github.com/teamclairvoyant/airflow-maintenance-dags/issues/41

**Comment by sudhakar-nallam** [comment]
This was taken care in the PR #57
