### ISSUE TITLE
Import error while execution of script

### ISSUE THREAD

**Issue by ajay999aj** [teamclairvoyant/airflow-maintenance-dags#58]
Hi,

iam getting bvelow import error / syntax error while executing the script in airflow container

[2019-10-31 09:47:52,516] {models.py:377} ERROR - Failed to import: /usr/local/airflow/dags/airflow_clear_missing_dags.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 374, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/airflow_clear_missing_dags.py", line 52
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Could you please help me,if you have a solution / fix for this?

thanks

**Comment by rssanders3** [comment]
Hello @ajay999aj, for python 3.6 you could adjust this `except Exception, e:` section on line 52 to be `except Exception as e:` instead.

**Comment by rssanders3** [comment]
Hello @ajay999aj, I updated the DAG to include the syntax change I mentioned above. Can you pull the latest and check?
